<a href="https://colab.research.google.com/github/ShakerNoreldin/Excel-project/blob/main/math_reading_writing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 1- Get the data from the web site

In [9]:
!wget https://www.ethnicity-facts-figures.service.gov.uk/education-skills-and-training/7-to-11-years-old/reading-writing-and-maths-attainments-for-children-aged-7-to-11-key-stage-2/latest/downloads/ks2-reading-writing-and-maths-national.csv

--2023-08-21 03:56:12--  https://www.ethnicity-facts-figures.service.gov.uk/education-skills-and-training/7-to-11-years-old/reading-writing-and-maths-attainments-for-children-aged-7-to-11-key-stage-2/latest/downloads/ks2-reading-writing-and-maths-national.csv
Resolving www.ethnicity-facts-figures.service.gov.uk (www.ethnicity-facts-figures.service.gov.uk)... 18.65.3.48, 18.65.3.95, 18.65.3.39, ...
Connecting to www.ethnicity-facts-figures.service.gov.uk (www.ethnicity-facts-figures.service.gov.uk)|18.65.3.48|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 101570 (99K) [text/csv]
Saving to: ‘ks2-reading-writing-and-maths-national.csv’

ks2-reading-writing 100%[===================>]  99.19K   376KB/s    in 0.3s

2023-08-21 03:56:13 (376 KB/s) - ‘ks2-reading-writing-and-maths-national.csv’ saved [101570/101570]

In [ ]:
#2-importing important libraries

In [10]:
import pandas as pd
import seaborn as ssn
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
#3- Reading the data using pandas to deal with them

In [11]:
RWM = pd.read_csv("ks2-reading-writing-and-maths-national.csv",sep = ",")

In [ ]:
#4-Investigating data and get the first look at it

In [12]:
RWM.head(7)

,Measure,Ethnicity,Ethnicity_type,Time,Time_type,Geography,Geography_type,Geography_code,Gender,Age,FSM,Value,Value_type,Denominator,Numerator
0,Percentage of pupils reaching the key stage 2 ...,All,All,2018-2019,Academic Year,England,Country,E92000001,All,10-11,All,65,%,644377,418104
1,Percentage of pupils reaching the key stage 2 ...,All,All,2018-2019,Academic Year,England,Country,E92000001,All,10-11,FSM,47,%,108849,51495
2,Percentage of pupils reaching the key stage 2 ...,All,All,2018-2019,Academic Year,England,Country,E92000001,All,10-11,Non-FSM,68,%,535528,366609
3,Percentage of pupils reaching the key stage 2 ...,All,All,2018-2019,Academic Year,England,Country,E92000001,Boys,10-11,All,60,%,328777,197953
4,Percentage of pupils reaching the key stage 2 ...,All,All,2018-2019,Academic Year,England,Country,E92000001,Boys,10-11,FSM,42,%,55727,23457
5,Percentage of pupils reaching the key stage 2 ...,All,All,2018-2019,Academic Year,England,Country,E92000001,Boys,10-11,Non-FSM,64,%,273050,174496
6,Percentage of pupils reaching the key stage 2 ...,All,All,2018-2019,Academic Year,England,Country,E92000001,Girls,10-11,All,70,%,315595,220151

In [13]:
RWM.shape

(440, 15)

In [14]:
RWM.columns

Index(['Measure', 'Ethnicity', 'Ethnicity_type', 'Time', 'Time_type',
       'Geography', 'Geography_type', 'Geography_code', 'Gender', 'Age', 'FSM',
       'Value', 'Value_type', 'Denominator', 'Numerator'],
      dtype='object')

In [16]:
RWM.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 440 entries, 0 to 439
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Measure         440 non-null    object
 1   Ethnicity       440 non-null    object
 2   Ethnicity_type  440 non-null    object
 3   Time            440 non-null    object
 4   Time_type       440 non-null    object
 5   Geography       440 non-null    object
 6   Geography_type  440 non-null    object
 7   Geography_code  440 non-null    object
 8   Gender          440 non-null    object
 9   Age             440 non-null    object
 10  FSM             440 non-null    object
 11  Value           440 non-null    int64
 12  Value_type      440 non-null    object
 13  Denominator     440 non-null    int64
 14  Numerator       440 non-null    int64
dtypes: int64(3), object(12)
memory usage: 51.7+ KB

In [17]:
RWM.describe()

            Value    Denominator      Numerator
count  440.000000     440.000000     440.000000
mean    33.984091   34748.236364   13116.018182
std     27.588206   92889.332144   45110.081716
min      0.000000       5.000000       0.000000
25%      8.000000    1428.750000     229.250000
50%     21.000000    4866.000000    1248.000000
75%     62.250000   14570.250000    4419.000000
max     83.000000  644377.000000  418104.000000